- name: Create backup directory
  ansible.builtin.file:
    path: /opt/bitwarden/backup
    state: directory
    mode: '0700'
    owner: 'bitwarden'
    group: 'bitwarden'

- name: Create backup script
  vars:
    s3_bucket: "{{ lookup('env', 'S3_BUCKET') }}"
    backup_password: "{{ lookup('env', 'BACKUP_PASSWORD') }}"
  ansible.builtin.template:
    src: backup.sh.j2
    dest: /opt/bitwarden/backup/backup.sh
    mode: '0700'
    owner: 'bitwarden'
    group: 'bitwarden'

- name: Setup cron job for backups
  ansible.builtin.cron:
    name: "Backup to S3"
    job: "/opt/bitwarden/backup/backup.sh"
    minute: "0"
    hour: "3"
