- name: Update apt package index
  ansible.builtin.apt:
    update_cache: true

- name: Install required packages for AWS CLI
  ansible.builtin.apt:
    name:
      - curl
      - unzip
    state: present

- name: Download AWS CLI installer
  ansible.builtin.get_url:
    url: "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip"
    dest: "/tmp/awscliv2.zip"
    mode: '0700'

- name: Unzip AWS CLI installer
  ansible.builtin.unarchive:
    src: "/tmp/awscliv2.zip"
    dest: "/tmp"
    remote_src: true

- name: Run AWS CLI installer
  ansible.builtin.command: "/tmp/aws/install"
  args:
    creates: /usr/local/bin/aws

- name: Verify AWS CLI installation
  ansible.builtin.command: "aws --version"
  register: aws_cli_version
  changed_when: false

- name: Display AWS CLI version
  ansible.builtin.debug:
    msg: "{{ aws_cli_version.stdout }}"

- name: Create AWS credentials directory
  ansible.builtin.file:
    path: /home/bitwarden/.aws
    state: directory
    mode: '0700'
    owner: 'bitwarden'
    group: 'bitwarden'

- name: Configure AWS credentials
  environment:
    aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY') }}"
    aws_secret_key: "{{ lookup('env', 'AWS_SECRET_KEY') }}"
  ansible.builtin.template:
    src: aws_credentials.j2
    dest: /home/bitwarden/.aws/credentials
    mode: '0600'
    owner: 'bitwarden'
    group: 'bitwarden'
